/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.accumulo.core.clientImpl.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class TNamespace implements org.apache.thrift.TBase<TNamespace, TNamespace._Fields>, java.io.Serializable, Cloneable, Comparable<TNamespace> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TNamespace");

  private static final org.apache.thrift.protocol.TField NAMESPACE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("namespaceId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NAMESPACE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("namespaceName", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TNamespaceStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TNamespaceTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String namespaceId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String namespaceName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAMESPACE_ID((short)1, "namespaceId"),
    NAMESPACE_NAME((short)2, "namespaceName");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAMESPACE_ID
          return NAMESPACE_ID;
        case 2: // NAMESPACE_NAME
          return NAMESPACE_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAMESPACE_ID, new org.apache.thrift.meta_data.FieldMetaData("namespaceId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NAMESPACE_NAME, new org.apache.thrift.meta_data.FieldMetaData("namespaceName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TNamespace.class, metaDataMap);
  }

  public TNamespace() {
  }

  public TNamespace(
    java.lang.String namespaceId,
    java.lang.String namespaceName)
  {
    this();
    this.namespaceId = namespaceId;
    this.namespaceName = namespaceName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TNamespace(TNamespace other) {
    if (other.isSetNamespaceId()) {
      this.namespaceId = other.namespaceId;
    }
    if (other.isSetNamespaceName()) {
      this.namespaceName = other.namespaceName;
    }
  }

  public TNamespace deepCopy() {
    return new TNamespace(this);
  }

  @Override
  public void clear() {
    this.namespaceId = null;
    this.namespaceName = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNamespaceId() {
    return this.namespaceId;
  }

  public TNamespace setNamespaceId(@org.apache.thrift.annotation.Nullable java.lang.String namespaceId) {
    this.namespaceId = namespaceId;
    return this;
  }

  public void unsetNamespaceId() {
    this.namespaceId = null;
  }

  /** Returns true if field namespaceId is set (has been assigned a value) and false otherwise */
  public boolean isSetNamespaceId() {
    return this.namespaceId != null;
  }

  public void setNamespaceIdIsSet(boolean value) {
    if (!value) {
      this.namespaceId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getNamespaceName() {
    return this.namespaceName;
  }

  public TNamespace setNamespaceName(@org.apache.thrift.annotation.Nullable java.lang.String namespaceName) {
    this.namespaceName = namespaceName;
    return this;
  }

  public void unsetNamespaceName() {
    this.namespaceName = null;
  }

  /** Returns true if field namespaceName is set (has been assigned a value) and false otherwise */
  public boolean isSetNamespaceName() {
    return this.namespaceName != null;
  }

  public void setNamespaceNameIsSet(boolean value) {
    if (!value) {
      this.namespaceName = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case NAMESPACE_ID:
      if (value == null) {
        unsetNamespaceId();
      } else {
        setNamespaceId((java.lang.String)value);
      }
      break;

    case NAMESPACE_NAME:
      if (value == null) {
        unsetNamespaceName();
      } else {
        setNamespaceName((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NAMESPACE_ID:
      return getNamespaceId();

    case NAMESPACE_NAME:
      return getNamespaceName();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NAMESPACE_ID:
      return isSetNamespaceId();
    case NAMESPACE_NAME:
      return isSetNamespaceName();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TNamespace)
      return this.equals((TNamespace)that);
    return false;
  }

  public boolean equals(TNamespace that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_namespaceId = true && this.isSetNamespaceId();
    boolean that_present_namespaceId = true && that.isSetNamespaceId();
    if (this_present_namespaceId || that_present_namespaceId) {
      if (!(this_present_namespaceId && that_present_namespaceId))
        return false;
      if (!this.namespaceId.equals(that.namespaceId))
        return false;
    }

    boolean this_present_namespaceName = true && this.isSetNamespaceName();
    boolean that_present_namespaceName = true && that.isSetNamespaceName();
    if (this_present_namespaceName || that_present_namespaceName) {
      if (!(this_present_namespaceName && that_present_namespaceName))
        return false;
      if (!this.namespaceName.equals(that.namespaceName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetNamespaceId()) ? 131071 : 524287);
    if (isSetNamespaceId())
      hashCode = hashCode * 8191 + namespaceId.hashCode();

    hashCode = hashCode * 8191 + ((isSetNamespaceName()) ? 131071 : 524287);
    if (isSetNamespaceName())
      hashCode = hashCode * 8191 + namespaceName.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TNamespace other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetNamespaceId()).compareTo(other.isSetNamespaceId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNamespaceId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.namespaceId, other.namespaceId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNamespaceName()).compareTo(other.isSetNamespaceName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNamespaceName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.namespaceName, other.namespaceName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TNamespace(");
    boolean first = true;

    sb.append("namespaceId:");
    if (this.namespaceId == null) {
      sb.append("null");
    } else {
      sb.append(this.namespaceId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("namespaceName:");
    if (this.namespaceName == null) {
      sb.append("null");
    } else {
      sb.append(this.namespaceName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TNamespaceStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TNamespaceStandardScheme getScheme() {
      return new TNamespaceStandardScheme();
    }
  }

  private static class TNamespaceStandardScheme extends org.apache.thrift.scheme.StandardScheme<TNamespace> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TNamespace struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAMESPACE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.namespaceId = iprot.readString();
              struct.setNamespaceIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAMESPACE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.namespaceName = iprot.readString();
              struct.setNamespaceNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TNamespace struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.namespaceId != null) {
        oprot.writeFieldBegin(NAMESPACE_ID_FIELD_DESC);
        oprot.writeString(struct.namespaceId);
        oprot.writeFieldEnd();
      }
      if (struct.namespaceName != null) {
        oprot.writeFieldBegin(NAMESPACE_NAME_FIELD_DESC);
        oprot.writeString(struct.namespaceName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TNamespaceTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TNamespaceTupleScheme getScheme() {
      return new TNamespaceTupleScheme();
    }
  }

  private static class TNamespaceTupleScheme extends org.apache.thrift.scheme.TupleScheme<TNamespace> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TNamespace struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetNamespaceId()) {
        optionals.set(0);
      }
      if (struct.isSetNamespaceName()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetNamespaceId()) {
        oprot.writeString(struct.namespaceId);
      }
      if (struct.isSetNamespaceName()) {
        oprot.writeString(struct.namespaceName);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TNamespace struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.namespaceId = iprot.readString();
        struct.setNamespaceIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.namespaceName = iprot.readString();
        struct.setNamespaceNameIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
  private static void unusedMethod() {}
}

